[package]
name = "ether_space"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.4"
rand = "0.8.5"
sdl2 = "0.36.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"
