name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL
      run: sudo apt-get install libsdl2-dev
    - name: Build
      run: cargo build --verbose
    - name: Release Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
